"""field users changee

Revision ID: 04a94bbc799f
Revises: 9425a334e4fd
Create Date: 2025-04-02 17:08:23.653155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04a94bbc799f'
down_revision: Union[str, None] = '9425a334e4fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bug', ['id'])
    op.create_unique_constraint(None, 'project', ['id'])
    op.create_unique_constraint(None, 'project_member', ['id'])
    op.create_unique_constraint(None, 'user', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'project_member', type_='unique')
    op.drop_constraint(None, 'project', type_='unique')
    op.drop_constraint(None, 'bug', type_='unique')
    # ### end Alembic commands ###
