"""Initial migrationaa

Revision ID: 35a7af11982d
Revises: 416d3fdd724b
Create Date: 2025-04-03 13:26:30.919495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35a7af11982d'
down_revision: Union[str, None] = '416d3fdd724b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bug', 'updatedById',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bug', 'updatedById',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
