"""On delete model

Revision ID: 36cd0d35b9d4
Revises: 35a7af11982d
Create Date: 2025-04-04 11:17:16.246442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36cd0d35b9d4'
down_revision: Union[str, None] = '35a7af11982d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bug', 'createdById',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('bug_projectId_fkey', 'bug', type_='foreignkey')
    op.create_foreign_key(None, 'bug', 'project', ['projectId'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(None, 'note', ['id'])
    op.drop_constraint('note_bugId_fkey', 'note', type_='foreignkey')
    op.create_foreign_key(None, 'note', 'bug', ['bugId'], ['id'], ondelete='CASCADE')
    op.alter_column('project', 'createdById',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project', 'createdById',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.create_foreign_key('note_bugId_fkey', 'note', 'bug', ['bugId'], ['id'])
    op.drop_constraint(None, 'note', type_='unique')
    op.drop_constraint(None, 'bug', type_='foreignkey')
    op.create_foreign_key('bug_projectId_fkey', 'bug', 'project', ['projectId'], ['id'])
    op.alter_column('bug', 'createdById',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
